version: '3'
networks:
  default:
    external:
      name: osslmansibleresourcemanager_default
services:
  alm-osm-rm:
     build:
       context: ./osm-adaptor
       dockerfile: Dockerfile
     ports:
       - "8081:8081"
     volumes:
       - "./var_alm_osm_rm/driver:/var/alm_osm_rm"
     environment:
       - LOG_LEVEL=DEBUG
       - LOG_FOLDER=/var/alm_osm_rm/logs
     extra_hosts:
       - "kafka:192.168.63.179"
